# Generated by Django 4.2.6 on 2024-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=46)),
                ('painting', models.ImageField(upload_to='gallery/images')),
                ('poem', models.TextField()),
            ],
        ),
    ]
